### ISSUE TITLE
Videos don't autoplay

### ISSUE THREAD

**Issue by jarhill0** [frankdai320/music2#1]
When loading a page such as https://telegramusic.ml/122, the video doesn't automatically start. In addition, when it finishes, it doesn't auto-redirect to the next video.

It looks like the cause is that cross-origin protection is failing. Viewing the source of the above page shows the following:

```html
<iframe id="player" type="text/html" width="640" height="390" src="https://www.youtube-nocookie.com/embed/OqBuXQLR4Y8?enablejsapi=1&rel=0&playsinline=1&origin=206.110.253.202&iv_load_policy=3"
```

The important part is this: `&origin=206.110.253.202`. The `origin` parameter should not be an IP address. It should be a domain name.

Check out the source of this bug:

https://github.com/frankdai320/music2/blob/8c799bb0956993cdb2a01c3acb8843011e97bc87/main.py#L39

`domain=request.remote_addr`

That should probably be something else.

**Comment by frankdai320** [comment]
Fixed in 1e339df1e5b7f6085a3a320876c32452f1a45303.
