### ISSUE TITLE
Previously valid URLs are suddenly invalid.

### ISSUE THREAD

**Issue by jarhill0** [frankdai320/music2#2]
URLs like https://telegramusic.ml/122/ which may exist in some users' browser autocomplete or which may be shared on chat platforms like Telegram now result in a 404.

The fix for this is to add trailing slashes to all the routes. This will preserve previous behavior, where a URL without a slash redirects to one with a slash.

See [this](https://www.tutorialspoint.com/flask/flask_variable_rules.htm) — scroll down to "Consider the rules defined in the following script."

**Comment by frankdai320** [comment]
Fixed in d5009402477c5f936fad36f2a467ebd7a7c1b953.
